config/routes.rb
Rails.application.routes.draw do

    resources :users

    resources :sessions, only: [:new, :create] do
      delete :destroy, on: :collection
    end

  get "welcome" => "welcome#index"
  root 'welcome#index'
  post "products/new" => "products#create"

    resources :products

end

app/models/product.rb
class Product < ActiveRecord::Base

  validates :title, { presence:  true,
                      uniqueness:  { message: "Product already exists!"},
                      length:      { minimum: 3}}
  validates :price, { presence:  true }


  validates :info, { presence:  true,

                     length:      { minimum: 3}}


end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  validates :email, presence: true, uniqueness: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_user

    unless user_signed_in?
      redirect_to new_session_path, alert: "Please sign in!"
    end
  end

  def current_user
    @current_user ||= User.find_by_id session[:user_id] if session[:user_id]
    end
    
    helper_method :current_user


  def user_signed_in?
    current_user.present?
  end

  helper_method :user_signed_in?


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def new
    authenticate_user
    @product = Product.new
  end

  def create
    @product = Product.new(params.require(:product).permit(:title, :price, :info))

    if @product.save
    redirect_to product_path(@product), notice: "Spatula Spawned!!"
    else
    render :new, notice: "Not saved!"
    end
  end

  def show
    @product = Product.find params[:id]
  end

  def destroy
    @product = Product.find params[:id]
    @product.destroy
    redirect_to products_path
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by_email params[:email]

    if user && user.authenticate(params[:password])

      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged in!"
    else
      flash[:alert] = "Wrong Credentials!"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged Out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).
          permit(:first_name, :last_name,
          :email, :password, :password_confirmation)
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "User Saved!"
    else
      render '/users/new', alert: "Not Saved!"
    end
  end

  def destroy
    @user = User.find params[:id]
    if @user.destroy
      redirect_to users_path,
      notice: "Deleted User!"
    else
      render 'index'
    end
  end





end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @products = Product.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_nav.html.erb
<%= link_to "Welcome", welcome_path %>
<%= link_to "New Product", new_product_path %>
<%= link_to "Product Index", products_path %>
<%= link_to "User Index", users_path %><br>

<% if user_signed_in?  %>
Hello <%= current_user.first_name %>
<%= link_to "Log Out", sessions_path, method: :delete %>
<% else %>
<%= link_to "Sign In", new_session_path %>
|
<%= link_to "Sign Up", new_user_path %><br>
<% end %>

<img src="/assets/images.jpg" width="150px" height="100px" alt="" />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SpatulaCity</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for :product do |f| %>

  <% if @product.errors.any? %>
  <div id="error_explanation">

  <h2>
    <%= pluralize  @product.errors.count, "error" %> prohibited this product from being saved:
    </h2>
    <ul>
<% @product.errors.full_messages.each do |error| %>
      <li><%= error %></li>
      <% end %>
    </ul>
  </div>
  <% end %>



<div class="">
<%= f.label :title %>
<%= f.text_field :title %>
</div><br>
<div class="">
<%= f.label :price %>
<%= f.text_field :price, data: {autonumeric: {aSign: 'CAD ', mDec: 0}} %>
</div><br>
<div class="">
<%= f.label :info %>
</div>

<div class="">
<%= f.text_area :info %>
</div>
<%= f.submit %>
<% end %>

app/views/products/index.html.erb
<%= render "/layouts/nav" %>
<%= link_to "New Product", new_product_path %>
<br>
<table>
  <tr>
    <th>Title: </th>
    <th>Price: </th>
    <th>Info: </th>
    <th><colspan="4"></th>
  </tr>

<% @products.each do |product| %>

  <tr>
    <td><%= product.title %></td>
    <td><%= product.price %></td>
    <td><%= product.info %></td>
  <td><%= link_to "Show", product_path(product) %></td>
  <td><%= link_to "Edit", products_path(product) %></td>
  <td><%= link_to "Destroy", product_path(product),
                            method: :delete,
                            data: { confirm: "Confirm Deletion?"}
                            %></td>
  </tr>
<% end %>
</table>

app/views/products/new.html.erb
<%= render "/layouts/nav" %>
<h1>Create a new spatula!! </h1>

<%= render "form" %>

app/views/products/show.html.erb
<%= render "nav" %>

<h2>Products</h2>
<br>

<%= @product.title  %><br><br><br>
<%= @product.price  %><br><br><br>
<%= @product.info  %><br><br>

<%= link_to "Index", products_path %>

app/views/users/index.html.erb
<%= render "/layouts/nav" %>

<% @users.each do |user| %>

<ol>
  <li><%= user.first_name  %></li>
  <li><%= user.last_name  %></li>
  <li><%= user.email  %></li>
  <li><%= user.password  %></li>
  <li><%= user.password_confirmation  %></li>
  <li><%= link_to "Delete", user_path(user),
                            method: :delete,
                            data: {confirm: "Confirm Deletion?"} %></li>
  <li><%= link_to "Edit", edit_user_path(user) %></li>
</ol>
<% end %>

app/views/users/new.html.erb
<%= render "/layouts/nav" %>

<h1>Sign up</h1>

<%= @user.errors.full_messages.join(", ") %>

<%= form_for @user do |f| %>

  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.text_field :password_confirmation, class: "form-control" %>
  </div>

  <%= f.submit class: "btn btn-primary" %>

  <% end %>

app/views/welcome/index.html.erb
<%= render "/layouts/nav" %>
<h1>Welcome to Spatula City!</h1>

<h2>We sell Spatulas, and that's <i>all!!</i></h2>

<% @products.each do |product| %>

<table>
  <tr>
    <td><%= product.title %></td>
    <td><%= product.price %></td>
    <td><%= product.info %></td>
    <td><%= link_to "Show", product_path(product) %></td>


  </tr>
</table>


<% end %>